//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> RestaurantID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> MainMenuID { get; set; }
        public Nullable<int> mySubMenuID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> SentToKitchenDate { get; set; }
        public string SentToKitchenTime { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public string CancellationTime { get; set; }
        public string CancelaltionReason { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryTime { get; set; }
        public Nullable<int> OrderStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MainMenu MainMenu { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
