//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu
    {
        public int mySubMenuID { get; set; }
        public Nullable<int> MainMenuID { get; set; }
        public string SubMenu1 { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual MainMenu MainMenu { get; set; }
    }
}
